"""create measurements

Revision ID: e61ef860989d
Revises: 61e68c996d17
Create Date: 2026-10-09 17:45:11.870119

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e61ef860989d"
down_revision: str | Sequence[str] | None = "61e68c996d17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurement_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "measurement_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("site", sa.String(), nullable=False),
        sa.Column("reading", sa.Integer(), nullable=False),
        sa.Column("value_cm", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["measurement_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "site", "reading"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("measurement_readings")
    op.drop_table("measurement_sessions")
    # ### end Alembic commands ###
